### ISSUE TITLE
Error serializing message Object already installed

### ISSUE THREAD

**Issue by johnou** [orbit/orbit#211]
Exception popped up in production.

```text
2017-01-24 19:53:14,066 ERROR [ForkJoinPool-1-worker-23] (cloud.orbit.actors.runtime.SerializationHandler) Error serializing message
java.lang.IllegalArgumentException: Object already installed: com.sulake.h4k.common.actors.observers.SessionObserver:jUP6WdiZRUFC4FoXdlVWpC
	at cloud.orbit.actors.runtime.LocalObjects.registerLocalObject(LocalObjects.java:235) ~[orbit-runtime-0.9.12.jar:?]
	at cloud.orbit.actors.runtime.LocalObjects.registerLocalObject(LocalObjects.java:216) ~[orbit-runtime-0.9.12.jar:?]
	at cloud.orbit.actors.runtime.LocalObjects.getOrAddLocalObjectReference(LocalObjects.java:188) ~[orbit-runtime-0.9.12.jar:?]
	at cloud.orbit.actors.Stage.registerObserver(Stage.java:1126) ~[orbit-runtime-0.9.12.jar:?]
	at cloud.orbit.actors.runtime.BasicRuntime.registerObserver(BasicRuntime.java:82) ~[orbit-core-0.9.12.jar:?]
	at cloud.orbit.actors.runtime.JavaMessageSerializer$1.replaceObject(JavaMessageSerializer.java:125) ~[orbit-runtime-0.9.12.jar:?]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1144) ~[?:1.8.0_102]
	at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378) ~[?:1.8.0_102]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174) ~[?:1.8.0_102]
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348) ~[?:1.8.0_102]
	at cloud.orbit.actors.runtime.JavaMessageSerializer.serializeMessage(JavaMessageSerializer.java:91) ~[orbit-runtime-0.9.12.jar:?]
	at cloud.orbit.actors.runtime.SerializationHandler.write(SerializationHandler.java:69) ~[orbit-runtime-0.9.12.jar:?]
	at cloud.orbit.actors.net.DefaultHandlerContext.write(DefaultHandlerContext.java:171) ~[orbit-runtime-0.9.12.jar:?]
	at cloud.orbit.actors.runtime.MessageLoopback.write(MessageLoopback.java:94) ~[orbit-runtime-0.9.12.jar:?]
	at cloud.orbit.actors.net.DefaultHandlerContext.write(DefaultHandlerContext.java:171) ~[orbit-runtime-0.9.12.jar:?]
	at cloud.orbit.actors.runtime.Messaging.writeMessage(Messaging.java:396) ~[orbit-runtime-0.9.12.jar:?]
	at cloud.orbit.actors.runtime.Messaging.writeInvocation(Messaging.java:358) ~[orbit-runtime-0.9.12.jar:?]
	at cloud.orbit.actors.runtime.Messaging.write(Messaging.java:318) ~[orbit-runtime-0.9.12.jar:?]
	at cloud.orbit.actors.net.DefaultHandlerContext.write(DefaultHandlerContext.java:171) ~[orbit-runtime-0.9.12.jar:?]
	at cloud.orbit.actors.runtime.Hosting.async$writeInvocation(Hosting.java:741) ~[orbit-runtime-0.9.12.jar:?]
	at cloud.orbit.concurrent.TaskContext.lambda$wrap$3(TaskContext.java:256) ~[orbit-commons-0.9.12.jar:?]
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_102]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_102]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_102]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962) ~[?:1.8.0_102]
	at cloud.orbit.concurrent.Task.internalComplete(Task.java:122) ~[orbit-commons-0.9.12.jar:?]
	at cloud.orbit.concurrent.Task.lambda$from$1(Task.java:173) ~[orbit-commons-0.9.12.jar:?]
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822) ~[?:1.8.0_102]
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797) ~[?:1.8.0_102]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_102]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962) ~[?:1.8.0_102]
	at cloud.orbit.concurrent.Task.internalComplete(Task.java:122) ~[orbit-commons-0.9.12.jar:?]
	at cloud.orbit.concurrent.Task.lambda$from$1(Task.java:173) ~[orbit-commons-0.9.12.jar:?]
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822) [?:1.8.0_102]
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797) [?:1.8.0_102]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) [?:1.8.0_102]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1595) [?:1.8.0_102]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582) [?:1.8.0_102]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_102]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_102]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_102]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_102]
```

**Comment by JoeHegarty** [comment]
That's a new one to me. Any idea on the circumstances?

**Comment by johnou** [comment]
Not yet, could just be high load.

**Comment by johnou** [comment]
I suspect it arises when using the same new observer with two actors concurrently.
