### ISSUE TITLE
Observer method may be invoked from JGroups thread

### ISSUE THREAD

**Issue by johnou** [orbit/orbit#213]
Blocking IO method invoked from observer may disrupt JGroups..

```text
2017-02-13T11:44:54,076 INFO  [Incoming-4,xxx,xxx] (xxx) gotcha []
java.lang.RuntimeException: null
	at xx
	at SimpleLocalEventDispatcher.publishEvent(SimpleLocalEventDispatcher.java:18) ~[classes/:?]
	at SimpleLocalEventDispatcher$ObjectInvoker.invoke(SimpleLocalEventDispatcher$ObjectInvoker.java) ~[classes/:?]
	at cloud.orbit.actors.runtime.ObjectInvoker.safeInvoke(ObjectInvoker.java:62) ~[orbit-core-0.9.12.jar:?]
	at cloud.orbit.actors.runtime.InvocationHandler.invoke(InvocationHandler.java:155) ~[orbit-runtime-0.9.12.jar:?]
	at cloud.orbit.actors.runtime.Execution.performInvocation(Execution.java:167) ~[orbit-runtime-0.9.12.jar:?]
	at cloud.orbit.actors.runtime.Execution.lambda$null$0(Execution.java:90) ~[orbit-runtime-0.9.12.jar:?]
	at cloud.orbit.actors.runtime.ObserverEntry.run(ObserverEntry.java:65) ~[orbit-runtime-0.9.12.jar:?]
	at cloud.orbit.actors.runtime.Execution.lambda$onInvocation$1(Execution.java:89) ~[orbit-runtime-0.9.12.jar:?]
	at cloud.orbit.actors.runtime.InternalUtils.safeInvoke(InternalUtils.java:192) ~[orbit-runtime-0.9.12.jar:?]
	at cloud.orbit.actors.runtime.Execution.onInvocation(Execution.java:89) ~[orbit-runtime-0.9.12.jar:?]
	at cloud.orbit.actors.runtime.Execution.onRead(Execution.java:74) ~[orbit-runtime-0.9.12.jar:?]
	at cloud.orbit.actors.net.DefaultHandlerContext.fireRead(DefaultHandlerContext.java:118) ~[orbit-runtime-0.9.12.jar:?]
	at cloud.orbit.actors.net.DefaultHandlerContext.fireRead(DefaultHandlerContext.java:118) ~[orbit-runtime-0.9.12.jar:?]
	at cloud.orbit.actors.runtime.Hosting.onInvocation(Hosting.java:610) ~[orbit-runtime-0.9.12.jar:?]
	at cloud.orbit.actors.runtime.Hosting.onRead(Hosting.java:595) ~[orbit-runtime-0.9.12.jar:?]
	at cloud.orbit.actors.net.DefaultHandlerContext.fireRead(DefaultHandlerContext.java:118) ~[orbit-runtime-0.9.12.jar:?]
	at cloud.orbit.actors.runtime.Messaging.onMessageReceived(Messaging.java:195) ~[orbit-runtime-0.9.12.jar:?]
	at cloud.orbit.actors.runtime.Messaging.onRead(Messaging.java:150) ~[orbit-runtime-0.9.12.jar:?]
	at cloud.orbit.actors.net.DefaultHandlerContext.fireRead(DefaultHandlerContext.java:118) ~[orbit-runtime-0.9.12.jar:?]
	at cloud.orbit.actors.extensions.PipelineExtension.onRead(PipelineExtension.java:93) ~[orbit-core-0.9.12.jar:?]
	at cloud.orbit.actors.net.DefaultHandlerContext.fireRead(DefaultHandlerContext.java:118) ~[orbit-runtime-0.9.12.jar:?]
	at cloud.orbit.actors.runtime.SerializationHandler.onRead(SerializationHandler.java:160) ~[orbit-runtime-0.9.12.jar:?]
	at cloud.orbit.actors.net.DefaultHandlerContext.fireRead(DefaultHandlerContext.java:118) ~[orbit-runtime-0.9.12.jar:?]
	at cloud.orbit.actors.runtime.ClusterHandler.lambda$connect$0(ClusterHandler.java:70) ~[orbit-runtime-0.9.12.jar:?]
	at cloud.orbit.actors.cluster.JGroupsClusterPeer.doReceive(JGroupsClusterPeer.java:310) [orbit-infinispan-cluster-0.9.12.jar:?]
	at cloud.orbit.actors.cluster.JGroupsClusterPeer$1$1.receive(JGroupsClusterPeer.java:174) [orbit-infinispan-cluster-0.9.12.jar:?]
	at org.jgroups.JChannel.up(JChannel.java:768) [jgroups-3.6.11.Final.jar:3.6.11.Final]
	at org.jgroups.fork.ForkProtocolStack.up(ForkProtocolStack.java:157) [jgroups-3.6.11.Final.jar:3.6.11.Final]
	at org.jgroups.stack.Protocol.up(Protocol.java:426) [jgroups-3.6.11.Final.jar:3.6.11.Final]
	at org.jgroups.protocols.FORK.up(FORK.java:161) [jgroups-3.6.11.Final.jar:3.6.11.Final]
	at org.jgroups.protocols.FRAG2.up(FRAG2.java:182) [jgroups-3.6.11.Final.jar:3.6.11.Final]
	at org.jgroups.protocols.FlowControl.up(FlowControl.java:438) [jgroups-3.6.11.Final.jar:3.6.11.Final]
	at org.jgroups.stack.Protocol.up(Protocol.java:426) [jgroups-3.6.11.Final.jar:3.6.11.Final]
	at org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:294) [jgroups-3.6.11.Final.jar:3.6.11.Final]
	at org.jgroups.protocols.UNICAST3.deliverBatch(UNICAST3.java:1100) [jgroups-3.6.11.Final.jar:3.6.11.Final]
	at org.jgroups.protocols.UNICAST3.removeAndDeliver(UNICAST3.java:899) [jgroups-3.6.11.Final.jar:3.6.11.Final]
	at org.jgroups.protocols.UNICAST3.handleDataReceived(UNICAST3.java:803) [jgroups-3.6.11.Final.jar:3.6.11.Final]
	at org.jgroups.protocols.UNICAST3.up(UNICAST3.java:433) [jgroups-3.6.11.Final.jar:3.6.11.Final]
	at org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:649) [jgroups-3.6.11.Final.jar:3.6.11.Final]
	at org.jgroups.protocols.BARRIER.up(BARRIER.java:152) [jgroups-3.6.11.Final.jar:3.6.11.Final]
	at org.jgroups.protocols.VERIFY_SUSPECT.up(VERIFY_SUSPECT.java:155) [jgroups-3.6.11.Final.jar:3.6.11.Final]
	at org.jgroups.protocols.FD_ALL.up(FD_ALL.java:200) [jgroups-3.6.11.Final.jar:3.6.11.Final]
	at org.jgroups.protocols.FD_SOCK.up(FD_SOCK.java:325) [jgroups-3.6.11.Final.jar:3.6.11.Final]
	at org.jgroups.protocols.MERGE3.up(MERGE3.java:292) [jgroups-3.6.11.Final.jar:3.6.11.Final]
	at org.jgroups.protocols.Discovery.up(Discovery.java:296) [jgroups-3.6.11.Final.jar:3.6.11.Final]
	at org.jgroups.protocols.TP.passMessageUp(TP.java:1657) [jgroups-3.6.11.Final.jar:3.6.11.Final]
	at org.jgroups.protocols.TP$SingleMessageHandler.run(TP.java:1873) [jgroups-3.6.11.Final.jar:3.6.11.Final]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_73]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_73]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]
```

**Comment by johnou** [comment]
@DanielSperry do you recall if this was intentional or perhaps an oversight?

**Comment by johnou** [comment]
Maybe something like this..

cloud.orbit.actors.runtime.ObserverEntry

```java
    @Override
    public <R> Task<R> run(final TaskFunction<LocalObjects.LocalObjectEntry<T>, R> function)
    {
        return executionSerializer.offerJob(reference, () -> function.apply(ObserverEntry.this), 10000);
    }
```

**Comment by johnou** [comment]
We might want to do something about the hardcoded maxQueueSize but this is the same code as in ActorEntry.
