### ISSUE TITLE
java.lang.IllegalStateException: Timer already cancelled.

### ISSUE THREAD

**Issue by SebastianStehle** [orbit/orbit#401]
Hi,

I register three timers in by activate method, but I started to see the following exception now:

```
	at java.util.Timer.sched(Timer.java:397) ~[?:1.8.0_212]
	at java.util.Timer.schedule(Timer.java:193) ~[?:1.8.0_212]
	at cloud.orbit.actors.Stage.registerTimer(Stage.java:1353) ~[orbit-runtime-1.9.2.jar!/:?]
	at cloud.orbit.actors.runtime.AbstractActor.registerTimer(AbstractActor.java:174) ~[orbit-core-1.9.2.jar!/:?]
	at cloud.orbit.actors.runtime.AbstractActor.registerTimer(AbstractActor.java:189) ~[orbit-core-1.9.2.jar!/:?]
	at com.easierlife.rs.actors.HouseholdActorImpl.activateAsync(HouseholdActorImpl.java:79) ~[classes!/:1.0-SNAPSHOT]
	at cloud.orbit.actors.runtime.ActorEntry.activate(ActorEntry.java:148) ~[orbit-runtime-1.9.2.jar!/:?]
	at cloud.orbit.actors.runtime.ActorEntry.doRunInternal(ActorEntry.java:98) ~[orbit-runtime-1.9.2.jar!/:?]
	at cloud.orbit.actors.runtime.ActorEntry.doRun(ActorEntry.java:86) ~[orbit-runtime-1.9.2.jar!/:?]
	at cloud.orbit.actors.runtime.ActorEntry.lambda$run$0(ActorEntry.java:69) ~[orbit-runtime-1.9.2.jar!/:?]
	at cloud.orbit.actors.runtime.InternalUtils.safeInvoke(InternalUtils.java:192) ~[orbit-runtime-1.9.2.jar!/:?]
	at cloud.orbit.actors.concurrent.WaitFreeMultiExecutionSerializer.lambda$offerJob$2(WaitFreeMultiExecutionSerializer.java:90) ~[orbit-runtime-1.9.2.jar!/:?]
	at cloud.orbit.actors.runtime.InternalUtils.safeInvoke(InternalUtils.java:192) ~[orbit-runtime-1.9.2.jar!/:?]
	at cloud.orbit.actors.concurrent.WaitFreeExecutionSerializer.lambda$executeSerialized$0(WaitFreeExecutionSerializer.java:88) ~[orbit-runtime-1.9.2.jar!/:?]
	at cloud.orbit.actors.concurrent.WaitFreeExecutionSerializer.tryExecute(WaitFreeExecutionSerializer.java:134) ~[orbit-runtime-1.9.2.jar!/:?]
	at cloud.orbit.actors.concurrent.WaitFreeExecutionSerializer.lambda$tryExecute$1(WaitFreeExecutionSerializer.java:154) ~[orbit-runtime-1.9.2.jar!/:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) [?:1.8.0_212]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_212]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_212]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_212]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_212]
```

**Comment by JoeHegarty** [comment]
Are you able to provide the actual exception type/message?
